/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionMenu: typeof import('./src/components/Utils/ActionMenu.vue')['default']
    Alert: typeof import('./src/components/alert.vue')['default']
    copy: typeof import('./src/components/NewPackageForm copy.vue')['default']
    CustomAlert: typeof import('./src/components/Utils/custom-alert.vue')['default']
    CustomTreeNode: typeof import('./src/components/Directorios/CustomTreeNode.vue')['default']
    CustomTreeViewNode: typeof import('./src/components/Directorios/CustomTreeViewNode.vue')['default']
    Dialogshared: typeof import('./src/components/dialogshared.vue')['default']
    DialogShared: typeof import('./src/components/Shared/DialogShared.vue')['default']
    Directorio: typeof import('./src/components/Directorios/Directorio.vue')['default']
    DirectoryItem: typeof import('./src/components/Directorios/DirectoryItem.vue')['default']
    DirectoryViewer: typeof import('./src/components/Directorios/DirectoryViewer.vue')['default']
    FileUploaderNode: typeof import('./src/components/Directorios/FileUploaderNode.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Utils/loading.vue')['default']
    Login: typeof import('./src/components/Autentication/Login.vue')['default']
    NewPackageForm: typeof import('./src/components/Packages/NewPackageForm.vue')['default']
    Package: typeof import('./src/components/Packages/Package.vue')['default']
    PackageActionsMenu: typeof import('./src/components/PackageActionsMenu.vue')['default']
    PackageDetailsModal: typeof import('./src/components/Packages/PackageDetailsModal.vue')['default']
    PackageTable: typeof import('./src/components/Packages/PackageTable.vue')['default']
    ProgressLoading: typeof import('./src/components/Utils/progressLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusItem: typeof import('./src/components/Packages/StatusItem.vue')['default']
    UpdatePackageForm: typeof import('./src/components/Packages/UpdatePackageForm.vue')['default']
    UploadFiles: typeof import('./src/components/Files/UploadFiles.vue')['default']
    ViewPackage: typeof import('./src/components/Packages/ViewPackage.vue')['default']
    ViewPackageByTrakingNumer: typeof import('./src/components/ViewPackageByTrakingNumer.vue')['default']
  }
}
